'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '../../..');
const t8 = fs.readFileSync(path.join(root, 'scripts/test-entrypoint.sh'), 'utf8');
const t12 = fs.readFileSync(path.join(root, 'scripts/test-runner-queue.sh'), 'utf8');
assert.ok(t8.includes('e13-docsbuild.json'), 'T8 must identify the verifier artifact');
assert.ok(t8.includes('schemas/verify.schema.json'), 'T8 must validate the verifier artifact with its schema');
const statusLoop = t8.slice(t8.indexOf('for f in "$OUT"/*.json'), t8.indexOf('# 4.3: default agent command'));
assert.ok(statusLoop.includes('e13-docsbuild.json'), 'T8 must exclude verifier evidence from status validation/count');
const fixture = t12.slice(t12.indexOf('TGT="$TMP/target"'), t12.indexOf('TGTW="$TGT"'));
const configMatch = fixture.match(/printf '([^']+)'\s*>\s*pipeline\.config\.json/);
assert.ok(configMatch, 'T12 must write pipeline.config.json before the initial commit');
const cfg = JSON.parse(configMatch[1].replace(/\\n$/, ''));
assert.strictEqual(typeof cfg.verifyCommand, 'string');
assert.ok(Array.isArray(cfg.frozenPaths));
assert.ok(cfg.dependencies && typeof cfg.dependencies === 'object');
assert.strictEqual(cfg.scopePolicy, undefined, 'T12 fixture should represent a legacy optional-scope target');
assert.ok(fixture.indexOf('pipeline.config.json') < fixture.indexOf('git add -A && git commit'), 'T12 config must be frozen at the fork point');
const runq = t12.slice(t12.indexOf('runq()'), t12.indexOf('st()'));
assert.ok(!runq.includes('tee /dev/stderr'), 'T12 capture must work without /dev/stderr');
assert.ok(runq.includes('pipefail'), 'T12 must preserve runner exit status');
console.log('PASS: T8 and T12 pre-main test-driver alignment');
