'use strict';
const fs0=require('fs'),os=require('os'),path=require('path');
const AUTH_MODES=['chatgpt','api-key']; const auth=p=>path.join(p,'auth.json');
const root=()=>path.join(os.homedir(),'.multi-agent-pipelines','codex-auth');
const remedy=()=> 'no usable ChatGPT Codex session — run codex login (device authentication) on the host, then retry';
function valid(x){try{const v=JSON.parse(x),s=JSON.stringify(v);return !!v&&typeof v==='object'&&!Array.isArray(v)&&!Object.keys(v).every(k=>/api[_-]?key/i.test(k))&&/access|refresh|token|account|chatgpt/i.test(s)}catch{return false}}
function validateConfig(raw={}){const codexAuth=raw.codexAuth==null?'api-key':String(raw.codexAuth).toLowerCase();return AUTH_MODES.includes(codexAuth)?{ok:true,codexAuth,credentialName:codexAuth==='api-key'?'CODEX_API_KEY':null}:{ok:false,reason:`run.config.json: 'codexAuth' must be one of ${AUTH_MODES.join(' | ')}`}}
function copy(src,dst,fs=fs0){const tmp=`${dst}.tmp-${process.pid}-${Date.now()}`;fs.copyFileSync(src,tmp);fs.renameSync(tmp,dst)}
function withCacheLock(opts,fn){const fs=opts.fs||fs0,r=opts.cacheRoot,lock=path.join(r,'.lifecycle.lock'),start=Date.now(),retry=opts.retryMs||20,timeout=opts.timeoutMs||5000;const go=()=>{fs.mkdirSync(r,{recursive:true,mode:0o700});let fd;try{fd=fs.openSync(lock,'wx',0o600)}catch(e){if(e.code!=='EEXIST')throw e;try{if(Date.now()-fs.statSync(lock).mtimeMs>=(opts.staleMs===undefined?300000:opts.staleMs)){fs.unlinkSync(lock);return go()}}catch(x){if(x.code!=='ENOENT')throw x}if(Date.now()-start>=timeout)throw Error('Codex credential cache lifecycle lock timed out');return new Promise((resolve,reject)=>setTimeout(()=>{try{resolve(go())}catch(x){reject(x)}},retry))}const done=()=>{try{fs.closeSync(fd)}catch{}try{fs.unlinkSync(lock)}catch{}};try{const v=fn();if(v&&typeof v.then==='function')return v.then(x=>{done();return x},x=>{done();throw x});done();return v}catch(e){done();throw e}};return go()}
function preflight(o={}){if(o.mode!=='chatgpt')return {ok:true,cacheRoot:o.cacheRoot||root()};const fs=o.fs||fs0,env=o.env||process.env,home=o.codexHome||env.CODEX_HOME||path.join(os.homedir(),'.codex'),r=o.cacheRoot||root();try{if(!valid(fs.readFileSync(auth(home),'utf8')))return {ok:false,reason:remedy()};return withCacheLock({...o,cacheRoot:r,fs},()=>{copy(auth(home),auth(r),fs);return {ok:true,cacheRoot:r}})}catch{return {ok:false,reason:remedy()}}}
function stageTaskCache(o={}){const fs=o.fs||fs0,r=o.cacheRoot||root();return withCacheLock({...o,cacheRoot:r,fs},()=>{if(o.codexHome){if(!valid(fs.readFileSync(auth(o.codexHome),'utf8')))throw Error(remedy());copy(auth(o.codexHome),auth(r),fs)}if(!fs.existsSync(auth(r)))throw Error(remedy());const hostPath=path.join(r,'tasks',String(o.taskId||process.pid));fs.mkdirSync(hostPath,{recursive:true,mode:0o700});fs.copyFileSync(auth(r),auth(hostPath));const containerPath=o.containerPath||'/root/.codex';return {hostPath,containerPath,mount:`${hostPath}:${containerPath}:rw`,cacheRoot:r}})}
function releaseTaskCache(h={}){const fs=h.fs||fs0;if(!h.cacheRoot||!h.hostPath)return;return withCacheLock({cacheRoot:h.cacheRoot,fs,retryMs:h.retryMs,timeoutMs:h.timeoutMs},()=>{const f=auth(h.hostPath);if(fs.existsSync(f)&&valid(fs.readFileSync(f,'utf8')))copy(f,auth(h.cacheRoot),fs);fs.rmSync(h.hostPath,{recursive:true,force:true})})}
module.exports={AUTH_MODES,validateConfig,preflight,stageTaskCache,releaseTaskCache,withCacheLock};
