'use strict';
const os=require('os'),path=require('path'),fs0=require('fs'),crypto=require('crypto');
const AUTH_MODES=['api-key','chatgpt'],LOGIN_REMEDY='run `codex login` (or complete device login) on the host, then retry';
const defaultCacheRoot=()=>path.join(os.homedir(),'.pipeline-codex-chatgpt'),authFile=r=>path.join(r,'auth.json'),lockFile=r=>path.join(r,'.lane.lock');
function managed(t){try{const v=JSON.parse(t);return!!(v&&v.auth_mode==='chatgpt'&&v.tokens&&typeof v.tokens.refresh_token==='string'&&v.tokens.refresh_token.trim())}catch{return false}}
function validateConfig(r={}){const m=r.codexAuth==null?'api-key':r.codexAuth;return AUTH_MODES.includes(m)?{ok:true,codexAuth:m,credentialName:m==='api-key'?'CODEX_API_KEY':null}:{ok:false,reason:"codexAuth must be 'api-key' or 'chatgpt'"}}
function readManaged(f,fs=fs0){try{const t=fs.readFileSync(f,'utf8');return managed(t)?t:null}catch{return null}}
function atomicWrite(f,t,fs=fs0){const x=`${f}.${process.pid}.${crypto.randomBytes(6).toString('hex')}.tmp`;fs.writeFileSync(x,t,{mode:0o600});fs.chmodSync(x,0o600);try{fs.renameSync(x,f);fs.chmodSync(f,0o600)}catch(e){try{fs.unlinkSync(x)}catch{}throw e}}
function alive(o){if(!o||!Number.isInteger(o.pid)||o.pid<=0)return false;try{process.kill(o.pid,0);return true}catch(e){return e&&e.code==='EPERM'}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function withCacheLock(o={},fn){const fs=o.fs||fs0,root=path.resolve(o.cacheRoot||defaultCacheRoot()),lock=lockFile(root),retry=o.retryMs||25,timeout=o.timeoutMs===undefined?1000:o.timeoutMs,stale=o.staleMs===undefined?1000:o.staleMs,wait=o.wait===true;fs.mkdirSync(root,{recursive:true,mode:0o700});fs.chmodSync(root,0o700);const start=Date.now(),token=crypto.randomBytes(16).toString('hex');for(;;){try{const fd=fs.openSync(lock,'wx',0o600);fs.writeFileSync(fd,JSON.stringify({pid:process.pid,token,startedAt:Date.now()}));fs.closeSync(fd);let value;try{value=await fn();if(o.keepLock && value && typeof value==='object'){value._lock={lock,token};return value}return value}finally{if(!o.keepLock)try{if(JSON.parse(fs.readFileSync(lock,'utf8')).token===token)fs.unlinkSync(lock)}catch{}}}catch(e){if(e.code!=='EEXIST')throw e;let owner=null,age=0;try{owner=JSON.parse(fs.readFileSync(lock,'utf8'));age=Date.now()-fs.statSync(lock).mtimeMs}catch{age=Date.now()-start}if(owner&&alive(owner)){}else if((!owner&&age>stale)||(owner&&!alive(owner))){try{fs.unlinkSync(lock)}catch{}continue}if(!wait&&Date.now()-start>=timeout)throw new Error('ChatGPT credential lane is busy; wait for the active Codex worker');await sleep(retry)}}}
async function preflight(o={}){if(o.mode!=='chatgpt')return{ok:true,cacheRoot:o.cacheRoot||defaultCacheRoot()};const fs=o.fs||fs0,root=path.resolve(o.cacheRoot||defaultCacheRoot()),home=o.codexHome||(o.env&&o.env.CODEX_HOME)||path.join(os.homedir(),'.codex');try{return await withCacheLock({...o,cacheRoot:root},async()=>{const d=authFile(root);if(fs.existsSync(d))return readManaged(d,fs)?{ok:true,cacheRoot:root}:{ok:false,reason:LOGIN_REMEDY};const seed=readManaged(authFile(home),fs);if(!seed)return{ok:false,reason:LOGIN_REMEDY};atomicWrite(d,seed,fs);return{ok:true,cacheRoot:root}})}catch(e){return{ok:false,reason:/busy/i.test(e.message)?e.message:LOGIN_REMEDY}}}
async function stageTaskCache(o={}){const fs=o.fs||fs0,root=path.resolve(o.cacheRoot||defaultCacheRoot());return withCacheLock({...o,cacheRoot:root,wait:o.wait===true,keepLock:true},async()=>{const source=authFile(root);let text=readManaged(source,fs);if(!text&&o.codexHome)text=readManaged(authFile(o.codexHome),fs);if(!text)throw new Error(LOGIN_REMEDY);if(!fs.existsSync(source))atomicWrite(source,text,fs);const safe=String(o.taskId||'task').replace(/[^A-Za-z0-9_.-]/g,'-');fs.mkdirSync(path.join(root,'tasks'),{recursive:true,mode:0o700});const hostPath=fs.mkdtempSync(path.join(root,'tasks',safe+'-'));fs.chmodSync(hostPath,0o700);fs.writeFileSync(path.join(hostPath,'auth.json'),text,{mode:0o600});fs.chmodSync(path.join(hostPath,'auth.json'),0o600);return{hostPath,cacheRoot:root,containerPath:o.containerPath||'/root/.codex',mount:`${hostPath}:${o.containerPath||'/root/.codex'}:rw`,fs}})}
async function releaseTaskCache(h){const fs=h.fs||fs0;let error;try{const text=readManaged(path.join(h.hostPath,'auth.json'),fs);if(!text)throw new Error('task ChatGPT cache is not a managed session');atomicWrite(authFile(h.cacheRoot),text,fs);fs.rmSync(h.hostPath,{recursive:true,force:true})}catch(e){error=e}finally{try{if(h._lock && JSON.parse(fs.readFileSync(h._lock.lock,'utf8')).token===h._lock.token)fs.unlinkSync(h._lock.lock)}catch{}}if(error)throw error}
module.exports={AUTH_MODES,validateConfig,preflight,stageTaskCache,releaseTaskCache,withCacheLock,defaultCacheRoot};
