// Frozen acceptance test — repo-uw6: the freeze gate's brittleness lint
// (DESIGN.md §3.2, "below the panel, move 6"; change-log row `freeze-brittleness-lint`).
// Written before implementation, from the spec alone; criteria C1–C7. Plain Node,
// Docker-free, node built-ins only.
//
// Six deliberate choices, five of them forced by the panel:
//
//   * EVERY SHAPE FIRES ON A SET OF VARIANTS, never one line. One literal instance per
//     shape is passed with full marks by a detector implemented as a LOOKUP TABLE over
//     the four fixture lines — and C1's deleted-lines run cannot catch that, because a
//     text-keyed table fires on the brittle copy and not on the clean one. Variants
//     generated by transformation cannot be table-matched.
//
//   * THE NEAR-MISS PAIRS ARE THE POINT OF THE WHOLE SUITE. For each shape, one line that
//     must fire and one that must not, differing in exactly the feature the rule turns on.
//     Two of the four are verbatim house patterns from this repo's own frozen suites: six
//     suites compare two COMPUTED digests as their "writes nothing" guard, and repo-1cy
//     runs git against refs it created itself. A detector keyed on `createHash` or on
//     `git diff` flags all seven and is wrong — and scores full marks on C2.
//
//   * THE PROSE COMMENT AND THE DECOY SIT NEAR LINE 3, THE SHAPES AT LINE 30+. A lint that
//     greps prose reports line 3; one that reports the file but not the line reports 1;
//     one that matches the decoy reports the wrong line. One fixture is CRLF, which is
//     this working copy's reality and breaks a naive line counter.
//
//   * THE EXIT CODE IS ASSERTED IN BOTH DIRECTIONS AND PAIRED WITH "THE LINT FIRED". The
//     exit-code half alone is passed perfectly by a lint that is wired in and silently
//     returns nothing. The green and indeterminate arms catch an `if (findings.length)
//     return 1`, which is invisible on the red arm because red already exits 0.
//
//   * THE DIGEST IN C7 IS OVER A PURPOSE-BUILT TEMP REPO, paths sorted, content bytes
//     only, mtime excluded. Digesting the live checkout would sweep `.git`, the
//     git-ignored `runs/`, `tools/mapbuild/node_modules` and anything a concurrent sweep
//     is writing — red at random, for reasons unrelated to the lint.
//
//   * NO FIXTURE IS COMMITTED. `tools/run-acceptance.sh` executes every *.js and *.sh in
//     this directory AS A TEST, so a fixture beside this file would be run as one.
//     Everything is built at runtime under os.tmpdir(); the CRLF file is written with
//     explicit \r\n rather than relying on a checked-in file.
'use strict';
const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..', '..');
let failed = 0;
function check(name, cond) {
  console.log(`${cond ? 'ok' : 'FAIL'} - ${name}`);
  if (!cond) failed = 1;
}
function safe(label, fn, fallback) {
  try { return fn(); } catch (e) {
    check(`${label} must not throw (threw: ${e && e.message})`, false);
    return fallback;
  }
}
const gate = (() => {
  try { return require(path.join(ROOT, 'scripts', 'freeze-gate.js')); } catch { return null; }
})();
if (!gate) { check('scripts/freeze-gate.js loads', false); process.exit(1); }

const hasLint = typeof gate.brittleFindings === 'function' && typeof gate.lintSuite === 'function';
check('freeze-gate exports brittleFindings(text, file) and lintSuite(dirOrFile)', hasLint);

// --- fixture construction -------------------------------------------------------------

// Each shape file: a prose comment and a decoy near line 3, padding, then the variants at
// known lines from line 30. Returns { text, lines: {variantIndex -> lineNumber}, decoyLine }.
function shapeFile(prose, decoy, variants, eol) {
  const L = ['// fixture', '//', `// ${prose}`, decoy, ''];
  const decoyLine = 4;
  while (L.length < 29) L.push(`const pad${L.length} = ${L.length};`);
  const lines = [];
  for (const v of variants) {
    lines.push(L.length + 1);
    for (const part of v.split('\n')) L.push(part);
  }
  return { text: L.join(eol || '\n'), variantLines: lines, decoyLine };
}

const SHAPES = {
  'literal-name-list': {
    prose: 'this used to assert deepStrictEqual against a whole list of names',
    decoy: "const FIXTURE_FILES = ['a.js', 'b.js'];",
    variants: [
      "assert.deepStrictEqual(keys, ['alpha', 'beta', 'gamma']);",
      'assert.deepStrictEqual(names, ["one","two"]);',
      "assert.deepStrictEqual( Object.keys(cfg), [ 'aa', 'bb', 'cc', 'dd' ] );",
      "assert.deepStrictEqual(list,\n  ['x', 'y', 'z']);",
    ],
    nearMissFires: "assert.deepStrictEqual(order, ['first', 'second']);",
    nearMissClean: "const joined = path.join('tests', 'acceptance', 'demo');",
    nearMissWhy: 'a literal list used as an INPUT, not as the expected side',
  },
  'literal-count': {
    prose: 'this used to pin the catalogue at exactly thirty entries',
    decoy: 'assert(lines.length > 0);',
    variants: [
      'assert.strictEqual(rows.length, 30);',
      'assert(out.length === 7);',
      'assert.strictEqual(entries.length, 61);',
      'assert.strictEqual(\n  flavours.length, 12);',
    ],
    nearMissFires: 'assert.strictEqual(items.length, 4);',
    nearMissClean: 'assert.strictEqual(errors.length, 0);',
    nearMissWhy: 'a count of ZERO is almost never a catalogue',
  },
  'literal-digest': {
    prose: 'this used to hash the whole build and compare it to a checked-in digest',
    decoy: "check('unchanged', digestBefore === digestAfter);",
    variants: [
      "assert.strictEqual(sha1(tree), 'd41d8cd98f00b204e9800998ecf8427e');",
      'check("digest", hash === "abc123def4560789abc123def4560789");',
      "assert.equal(crypto.createHash('sha1').update(b).digest('hex'), '0123456789abcdef0123456789abcdef');",
      "assert.strictEqual(digestOf(dir),\n  'fedcba9876543210fedcba9876543210');",
    ],
    nearMissFires: "assert.strictEqual(treeHash, 'aaaabbbbccccddddeeeeffff00001111');",
    nearMissClean: 'assert.strictEqual(digestBefore, digestAfter);',
    nearMissWhy: 'two COMPUTED digests compared to each other — the house snapshot guard '
      + 'in six of this repo’s own frozen suites',
  },
  'branch-self-diff': {
    prose: 'this used to diff the branch against its own fork point over the source tree',
    decoy: "spawnSync('git', ['status', '--porcelain'], { cwd: tmp });",
    variants: [
      "spawnSync('git', ['diff', '--name-only', 'origin/main', 'HEAD']);",
      "run('git merge-base origin/master HEAD');",
      "spawnSync('git', ['diff', 'origin/main...HEAD', '--', 'src/']);",
      "spawnSync('git', ['merge-base',\n  'origin/main', 'HEAD']);",
    ],
    nearMissFires: "spawnSync('git', ['diff', '--name-only', 'origin/main', 'HEAD']);",
    nearMissClean: "spawnSync('git', ['diff', '--name-only', base, 'HEAD'], { cwd: throwaway });",
    nearMissWhy: 'git against a ref the test itself created in a throwaway repo — repo-1cy',
  },
};

// One shape's variants are written in GDScript rather than JavaScript, and one file is CRLF.
SHAPES['literal-count'].variants = [
  'assert_eq(rows.size(), 30)',
  'assert(out.size() == 7)',
  'assert_eq(entries.size(), 61)',
  'assert_eq(\n\tflavours.size(), 12)',
];
SHAPES['literal-count'].gdscript = true;
SHAPES['literal-digest'].crlf = true;

const built = {};
for (const [shape, s] of Object.entries(SHAPES)) {
  built[shape] = shapeFile(s.prose, s.decoy, s.variants, s.crlf ? '\r\n' : '\n');
}

// --- C2 — every variant fires, at its planted line, with its own shape token -------------

if (hasLint) {
  for (const [shape, s] of Object.entries(SHAPES)) {
    const b = built[shape];
    const file = `${shape}${s.gdscript ? '.gd' : '.js'}`;
    const found = safe(`C2 brittleFindings(${shape})`, () => gate.brittleFindings(b.text, file), []);
    const linesFor = (sh) => found.filter((f) => f.shape === sh).map((f) => f.line);
    const got = linesFor(shape);
    const missing = b.variantLines.filter((ln) => !got.includes(ln));
    check(`C2 ${shape}: all four variants fire, at their planted lines`
      + (missing.length ? ` (missing lines ${missing.join(',')}, got ${got.join(',') || 'none'})` : ''),
      missing.length === 0);
    check(`C2 ${shape}: the prose comment on line 3 is not reported as a finding`,
      !found.some((f) => f.line === 3));
    check(`C2 ${shape}: the decoy on line ${b.decoyLine} is not reported as this shape`,
      !linesFor(shape).includes(b.decoyLine));
    check(`C2 ${shape}: every finding names the file it was given`,
      found.length > 0 && found.every((f) => f.file === file));
  }
  check('C2 the CRLF fixture is line-counted correctly (literal-digest is CRLF)',
    built['literal-digest'].text.includes('\r\n'));
}

// --- C3 — the near-miss pairs -------------------------------------------------------------

if (hasLint) {
  for (const [shape, s] of Object.entries(SHAPES)) {
    const fires = safe(`C3 fires(${shape})`, () => gate.brittleFindings(s.nearMissFires, 'x.js'), []);
    const clean = safe(`C3 clean(${shape})`, () => gate.brittleFindings(s.nearMissClean, 'x.js'), []);
    check(`C3 ${shape}: the near-miss that MUST fire does`,
      fires.some((f) => f.shape === shape));
    check(`C3 ${shape}: the near-miss that must NOT fire does not — ${s.nearMissWhy}`,
      !clean.some((f) => f.shape === shape));
  }
  // The whole negative fixture: assertions this repo actually writes.
  const NEGATIVE = [
    "const r = spawnSync('node', [script]);",
    'assert.strictEqual(r.status, 0);',
    "check('summary names the queue', out.includes('ready queue:'));",
    'check("the suite printed a pass", /PASS/.test(out));',
    'check("something was produced", lines.length > 0);',
    "// [guard] existing behaviour still holds",
    'assert.strictEqual(digestBefore, digestAfter);',
    "const p = path.join('tests', 'acceptance', 'demo');",
    'assert.strictEqual(errors.length, 0);',
  ].join('\n');
  const neg = safe('C3 negative fixture', () => gate.brittleFindings(NEGATIVE, 'neg.js'), null);
  check('C3 a fixture of assertions this repo really writes yields ZERO findings'
    + (neg && neg.length ? ` (got ${neg.map((f) => `${f.shape}@${f.line}`).join(', ')})` : ''),
    Array.isArray(neg) && neg.length === 0);
}

// --- the CLI harness: a stubbed verify command over a temp repo ---------------------------

const tmpRepo = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-uw6-'));
const STUB = `
const fs = require('fs'); const p = process.argv[2];
const mode = process.env.STUB_MODE || 'honest';
if (String(p).indexOf('_control') >= 0) process.exit(0);
if (mode === 'always-green') process.exit(0);
if (mode === 'always-red') process.exit(4);
let n = 0; try { n = fs.readdirSync(p).length; } catch { n = 0; }
process.exit(n > 0 ? 1 : 0);
`;
const stubPath = path.join(tmpRepo, 'stub.js');
fs.writeFileSync(stubPath, STUB);
const q = (p) => `"${p.replace(/\\/g, '/')}"`;
process.env.FREEZE_GATE_CMD = `${q(process.execPath)} ${q(stubPath)}`;
fs.writeFileSync(path.join(tmpRepo, 'pipeline.config.json'),
  JSON.stringify({ verifyCommand: 'unused-because-stubbed', defaultBranch: 'main' }));
fs.writeFileSync(path.join(tmpRepo, 'spec.md'), '- [guard] existing behaviour X still holds\n');
// The conventional control (ONBOARDING.md §2): one trivially-passing test. Without it the
// gate falls back to the empty-directory probe and says so, which is a different label —
// and both labels are needed below, one run each.
const controlDir = path.join(tmpRepo, 'tests', 'acceptance', '_control');
fs.mkdirSync(controlDir, { recursive: true });
fs.writeFileSync(path.join(controlDir, 'control.js'), '// trivially passing\n');

// Two suites differing ONLY in the brittle lines.
const brittleDir = path.join(tmpRepo, 'tests', 'acceptance', 'brittle');
const cleanDir = path.join(tmpRepo, 'tests', 'acceptance', 'clean');
fs.mkdirSync(brittleDir, { recursive: true });
fs.mkdirSync(cleanDir, { recursive: true });
for (const [shape, s] of Object.entries(SHAPES)) {
  const name = `${shape}${s.gdscript ? '.gd' : '.js'}`;
  fs.writeFileSync(path.join(brittleDir, name), built[shape].text);
  const stripped = built[shape].text.split(/\r?\n/)
    .filter((l) => !s.variants.some((v) => v.split('\n').some((part) => part.trim() && l.trim() === part.trim())))
    .join('\n');
  fs.writeFileSync(path.join(cleanDir, name), stripped);
}

const capture = () => {
  const o = console.log; const e = console.error;
  let buf = '';
  console.log = (...a) => { buf += a.join(' ') + '\n'; };
  console.error = (...a) => { buf += a.join(' ') + '\n'; };
  return () => { console.log = o; console.error = e; return buf; };
};
const runMain = (args) => {
  const done = capture();
  let code;
  try { code = gate.main(args); } catch (err) { code = `threw: ${err && err.message}`; }
  return { code, out: done() };
};
const argsFor = (dir) => ['--repo', tmpRepo, '--tests', `tests/acceptance/${dir}/`];

// --- C1 — the exit code never moves, and the lint is proven to have fired ----------------

const MODES = [null, 'always-green', 'always-red'];
const EXPECT = [0, 1, 2];
const tripleBrittle = []; const tripleClean = []; const outsBrittle = [];
for (const m of MODES) {
  if (m) process.env.STUB_MODE = m; else delete process.env.STUB_MODE;
  const b = runMain(argsFor('brittle'));
  const c = runMain(argsFor('clean'));
  tripleBrittle.push(b.code); tripleClean.push(c.code); outsBrittle.push(b.out);
}
delete process.env.STUB_MODE;
check(`C1 the brittle suite exits 0/1/2 for red/green/broken-harness (got ${tripleBrittle.join('/')})`,
  JSON.stringify(tripleBrittle) === JSON.stringify(EXPECT));
check(`C1 the clean suite exits identically (got ${tripleClean.join('/')})`,
  JSON.stringify(tripleClean) === JSON.stringify(EXPECT));
const COUNT = /brittleness findings:\s*(\d+)/;
check('C1 and the lint is proven to have FIRED in each brittle run (n >= 4)',
  outsBrittle.every((o) => { const m = o.match(COUNT); return m && Number(m[1]) >= 4; }));

// --- C6 — the existing report survives, in all three verdicts and both invocations --------

check('C6 the count line prints in all three verdicts',
  outsBrittle.every((o) => COUNT.test(o)));
const withSpec = runMain([...argsFor('clean'), '--spec', path.join(tmpRepo, 'spec.md')]);
const noSpec = runMain(argsFor('clean'));
check('C6 the count line prints WITH --spec', COUNT.test(withSpec.out));
check('C6 the count line prints WITHOUT --spec — `guards declared:` lives inside if (spec)',
  COUNT.test(noSpec.out));
check('C6 `guards declared: 1` still appears verbatim', /guards declared: 1/.test(withSpec.out));
// The two control labels are MUTUALLY EXCLUSIVE within any one run — the gate prints
// either "_control/ — one passing test" or "empty directory — NO control fixture". A
// single-run assertion over all six strings is therefore a check no implementation can
// pass, so the no-control arm is taken with the fixture moved aside and restored at once.
const asideDir = path.join(tmpRepo, '_control-aside');
fs.renameSync(controlDir, asideDir);
const noControl = runMain(argsFor('clean'));
fs.renameSync(asideDir, controlDir);
check('C6 without a control fixture the gate still says so',
  /NO control fixture/.test(noControl.out));
const SIX = ['RED:', 'control run', 'guards declared: 1', 'NO control fixture', '_control',
  'one passing test'];
const allOut = outsBrittle.join('\n') + withSpec.out + noSpec.out + noControl.out;
const missingSix = SIX.filter((s) => !allOut.includes(s));
check(`C6 all six strings scripts/test-freeze-gate.sh greps for still appear`
  + (missingSix.length ? ` (missing: ${missingSix.join(' | ')})` : ''), missingSix.length === 0);
check('C6 a clean suite prints the count as ZERO, not silence',
  /brittleness findings:\s*0\b/.test(noSpec.out));

// --- C3/C6 — a path that throws on read does not take the verdict with it -----------------

const throwDir = path.join(tmpRepo, 'tests', 'acceptance', 'throws');
fs.mkdirSync(throwDir, { recursive: true });
fs.writeFileSync(path.join(throwDir, 'ok.js'), built['literal-name-list'].text);
// A directory where a readable file is expected: readdir/readFile throws EISDIR everywhere,
// for root and non-root alike. A chmod-000 file is unreadable in the container and fully
// readable on the Windows host, which would exercise a different branch in each place a
// frozen suite runs.
fs.mkdirSync(path.join(throwDir, 'trap.js'), { recursive: true });
const thrown = runMain(argsFor('throws'));
check('C6 a path that throws on read leaves the verdict at its exit code (0 = red)',
  thrown.code === 0);
check('C6 and the pass says so rather than printing a silent 0',
  /brittleness findings:\s*(unavailable|\d)/.test(thrown.out));

// --- C4 — the skip vocabulary is exact, and siblings are still linted ----------------------

if (hasLint) {
  const skipDir = path.join(tmpRepo, 'tests', 'acceptance', 'skips');
  fs.mkdirSync(skipDir, { recursive: true });
  fs.writeFileSync(path.join(skipDir, 'bin.js'), Buffer.from([0x41, 0x00, 0x42, 0x00, 0x43]));
  fs.writeFileSync(path.join(skipDir, 'image.png'), Buffer.from([0x89, 0x50, 0x4e, 0x47]));
  fs.writeFileSync(path.join(skipDir, 'good.js'), built['literal-name-list'].text);
  // NOTE: `unreadable` stays in the vocabulary for a read that throws, but is deliberately
  // NOT asserted here. There is no way to produce a genuinely unreadable file that behaves
  // the same in both places this suite runs — chmod-000 is unreadable in the container and
  // fully readable on the Windows host, and a directory named `x.js` is recursed into by
  // any reasonable walker rather than failing to read. A check that exercises a different
  // branch in each environment makes the freeze gate's verdict stop meaning what it says.
  const res = safe('C4 lintSuite(skips)', () => gate.lintSuite(skipDir), null);
  const skipped = (res && res.skipped) || [];
  const reasons = new Set(skipped.map((s) => s && s.reason));
  const named = (p) => skipped.some((s) => s && String(s.path).replace(/\\/g, '/').endsWith(p));
  check('C4 the NUL-byte file is skipped with reason `binary`',
    named('bin.js') && reasons.has('binary'));
  check('C4 the out-of-allowlist extension is skipped with reason `extension`',
    named('image.png') && reasons.has('extension'));
  check('C4 THE READABLE SIBLING IS STILL LINTED — the assertion that separates '
    + 'swallow-silently from abort-the-pass',
    !!res && Array.isArray(res.findings)
      && res.findings.some((f) => String(f.file).replace(/\\/g, '/').endsWith('good.js')));
  const skipOut = runMain(['--repo', tmpRepo, '--tests', 'tests/acceptance/skips/']);
  check('C4 every skipped path is named on stdout',
    ['bin.js', 'image.png'].every((n) => skipOut.out.includes(n)));
}

// --- C5 — the question is the deliverable, so its VALUE is pinned --------------------------

if (hasLint) {
  const qs = {};
  for (const [shape] of Object.entries(SHAPES)) {
    const f = safe(`C5 findings(${shape})`, () => gate.brittleFindings(built[shape].text,
      `${shape}.js`), []);
    const first = f.find((x) => x.shape === shape);
    qs[shape] = first ? String(first.question || '') : '';
  }
  const vals = Object.values(qs);
  check('C5 every shape carries a non-empty question', vals.every((v) => v.length > 0));
  check('C5 the four questions are pairwise DISTINCT — not one generic string reused',
    new Set(vals).size === vals.length);
  check('C5 each question names its own shape', Object.entries(qs).every(([shape, v]) => {
    const words = shape.split('-');
    return words.some((w) => v.toLowerCase().includes(w));
  }));
  // `text` is checkable against the fixture independently of the detector.
  const nl = built['literal-name-list'];
  const f0 = safe('C5 text field', () => gate.brittleFindings(nl.text, 'n.js'), []);
  const srcLines = nl.text.split(/\r?\n/);
  check('C5 each finding’s `text` equals the trimmed source line it sits on',
    f0.length > 0 && f0.every((f) => f.text === String(srcLines[f.line - 1] || '').trim()));
}

// --- C7 [guard] — the decision table is untouched and the gate writes nothing --------------

const TABLE = [
  [{ status: 1 }, { status: 0 }, 'conventional', 'red', 0],
  [{ status: 0 }, { status: 0 }, 'conventional', 'green', 1],
  [{ status: 2 }, { status: 0 }, 'conventional', 'indeterminate', 2],
  [{ status: 5 }, { status: 0 }, 'conventional', 'indeterminate', 2],
  [{ status: 1 }, { status: 1 }, 'conventional', 'indeterminate', 2],
  [{ status: 1 }, { status: 0 }, 'empty-probe', 'red', 0],
  [{ error: 'boom' }, { status: 0 }, 'conventional', 'indeterminate', 2],
  [{ signal: 'SIGKILL' }, { status: 0 }, 'conventional', 'indeterminate', 2],
  [{ status: null }, { status: 0 }, 'conventional', 'indeterminate', 2],
];
let tableOk = true;
for (const [real, ctl, kind, verdict, exit] of TABLE) {
  const v = safe('C7 verdictFor', () => gate.verdictFor(real, ctl, kind), null);
  if (!v || v.verdict !== verdict || v.exit !== exit) tableOk = false;
}
check('C7 [guard] verdictFor still answers all nine rows of the decision table exactly', tableOk);

// The digest: purpose-built temp repo, sorted paths, content bytes only, never mtime.
function digestOf(root) {
  const out = [];
  (function walk(d, rel) {
    let entries;
    try { entries = fs.readdirSync(d, { withFileTypes: true }); } catch { return; }
    for (const e of entries.map((x) => x.name).sort()) {
      const abs = path.join(d, e);
      const r = rel ? `${rel}/${e}` : e;
      let st; try { st = fs.statSync(abs); } catch { continue; }
      if (st.isDirectory()) walk(abs, r);
      else {
        let b; try { b = fs.readFileSync(abs); } catch { b = Buffer.alloc(0); }
        out.push(r + '\0' + crypto.createHash('sha1').update(b).digest('hex'));
      }
    }
  }(root, ''));
  return crypto.createHash('sha1').update(out.join('\n')).digest('hex');
}
const before = digestOf(tmpRepo);
runMain(argsFor('brittle'));
const after = digestOf(tmpRepo);
check('C7 [guard] a full run writes nothing to the target repo (sorted paths, bytes only)',
  before === after);

// --- cleanup -------------------------------------------------------------------------------
try { fs.rmSync(tmpRepo, { recursive: true, force: true }); } catch { /* best effort */ }

process.exit(failed);
